Develop
Stan8Dord/java-explore-with-me pull request #2
Opened 2023-01-14 01:45 UTC by Stan8Dord

2023-01-15 09:32 UTC, krylov-sergey-sergeevich requested changes
Привет, по бизнес логике вроде как нет замечаний, пройдемся по концептуальным моментам

- В pr есть папка target она разве должна быть?
-  Рекомендуется commit-message писать не просто для вида, а то что было действительно сделано.
- Во всех методах контроллера крайне желательно иметь лог на англ языке что происходит, это позволяет в последующем удобно разбирать ошибки
- Много где рекомендую использовать аннотацию для того чтобы не писать конструктор
- В некоторых местах можно получше попытаться подумать и избежать дублирования кода, для нахождения таких мест рекомендую самому смотреть pr сверху вниз, а не через IDEA
- Подход с исключениями хорош, но можно лучше. Исключения если присмотреться похожи по структуре, не хочется ли создать структуру исключений или побольше кастомных исключений и не писать каждый раз весь текст причины исключения, а чисто название например NotFoundCategoryException extend NotFoundException это не обязательно, но как на подумать. Плюс в исключениях ОБЯЗАТЕЛЬНО надо еще добавлять id объекта с которым проблема или действие.
- @JsonFormat - почитать и если понятно где и как применить то применить
- @UtillityClass lombok - давай накинем на утилитные классы 
- Нет класса Constants в который бы кидалась всякая мелочь которая статична на весь проект, рекомендую создать и пользоваться

На будущее после выполнения этой задачи почитать про:
- Swagger и Mapstruct

Буду ждать с доработками =)

2023-01-15 09:32 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/explorewithme/model/compilation/Compilation.java
> +    List<Event> events;
модифкатор доступа

2023-01-15 09:32 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/explorewithme/model/request/RequestMapper.java
> +    public static DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
public static DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

Вот такие штуки я предпочитаю выносить в класс Constants или DateUtils тк в коде часто их дубли возникают, давай поправим и сделаем чтобы было без дублей

2023-01-15 09:32 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/explorewithme/exceptions/ErrorHandler.java
> +public class ErrorHandler {
Попробуй поизучать как можно сделать так чтобы еще возвращать в сообщение с ошибкой request path по которому был сделан запрос. Один из вариантов это воспользоваться: **HttpServletRequest**

2023-01-16 00:24 UTC, Stan8Dord commented
Сергей, привет!

Спасибо за ревью. По всем пунктам внес улучшения в код проекта.

2023-01-16 15:28 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки, работа достойная - зачет!

Удачи =)

2023-01-17 09:26 UTC, merged